project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  favicon: static/bsa-favicon.png
  title: "Analytical Code Assurance" 
  navbar:
    title: false
    logo: "static/bsa-logo.png"
    logo-alt: "NHS Business Services Authority"
    logo-href: "https://www.nhsbsa.nhs.uk/"
    pinned: true
    background: "#005EB8"
    collapse: false
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
    tools:
      - icon: github
        href:  https://github.com/nhsbsa-data-analytics/nhsbsa-analytical-code-assurance-playbook
        
  sidebar:
    style: "docked"
    search: false
    collapse-level: 2
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Reproducible"
        href: guidance/01-reproducible/index.qmd
        contents: guidance/01-reproducible/pages/*
      - section: "Quality Assured"
        href: guidance/02-quality-assured/index.qmd
        contents: guidance/02-quality-assured/pages/*
      - section: "Transparent"
        href: guidance/03-transparent/index.qmd
        contents: guidance/03-transparent/pages/*
      
format:
  html:
   grid: 
    sidebar-width: 25%
   pagetitle: "Analytical Code Assurance"
   lang: en-GB
   theme: cosmo
   css: styles.css
   mainfont: "Arial"
   fontsize: 130%
   page-layout: full
   toc: true
    
execute:
  freeze: auto
