project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  favicon: static/bsa-favicon.png
  title: "Analytical Code Assurance"
  # Search is good to have and works very well. But it introduces an accessibility
  # issue no matter how it is configured.
  # https://quarto.org/docs/websites/website-search.html
  # overlay gives empty button, while textbox gives empty label
  # Disabled for now until a solution is found
  search: false
  navbar:
    title: false
    logo: "static/NHSBSA logo.png"
    logo-alt: "NHS Business Services Authority"
    logo-href: "https://www.nhsbsa.nhs.uk/"
    pinned: true
    background: "#005EB8"
    collapse: false
    left:
      - href: index.qmd
        text: Playbook Home Page
      - text: "Guidance"
        menu:
          - href: guidance/01-reproducible/index.qmd
          - href: guidance/02-quality-assured/index.qmd
          - href: guidance/03-transparent/index.qmd
          
    right:
      - href: about.qmd
        text: "{{< iconify mdi:information-outline size=xl >}} About"
      - href: https://www.nhsbsa.nhs.uk/nhsbsa-statistics-and-data-science
        text: "{{< iconify mdi:house-outline size=xl >}} NHSBSA Data Science Home Page"
      - href: https://github.com/nhsbsa-data-analytics/nhsbsa-analytical-code-assurance-playbook
        text: "{{< iconify mdi:github size=xl >}} GitHub"
      - href: https://twitter.com/nhsbsa
        text: "{{< iconify mdi:twitter size=xl >}} X (formerly Twitter)"
        
  announcement: 
    icon: info-circle
    dismissable: true
    content: '
      **Pre-Release**: This is a new website under development.
      [Click here](https://github.com/nhsbsa-data-analytics/nhsbsa-analytical-code-assurance-playbook/blob/main/CONTRIBUTE.md)
      to find out how you can submit feedback, suggest improvements and get involved!
      '
    type: warning
    position: above-navbar

  sidebar:
    style: "docked"
    search: false
    collapse-level: 2
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Reproducible"
        href: guidance/01-reproducible/index.qmd
        contents: guidance/01-reproducible/pages/*
      - section: "Quality Assured"
        href: guidance/02-quality-assured/index.qmd
        contents: guidance/02-quality-assured/pages/*
      - section: "Transparent"
        href: guidance/03-transparent/index.qmd
        contents: guidance/03-transparent/pages/*
        
  page-footer:
    left: |
      * [Accessibility](/accessibility.qmd)
      * [Contact](mailto:analyticalassurance@nhsbsa.nhs.uk)
      * [GitHub](https://github.com/nhsbsa-data-analytics/nhsbsa-analytical-code-assurance-playbook)
    
      <img src="/static/ogl3-logo.svg" height="17" width="41" focusable="false">&nbsp;
      All content is available under the <a class="nhsuk-footer__list-item-link" href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated.        
              
    right:
      - text: "&copy Crown Copyright"
      
format:
  html:
    grid: 
      sidebar-width: 25%
    pagetitle: "Analytical Code Assurance"
    lang: en-GB
    theme: cosmo
    css: styles.css
    mainfont: "Arial"
    fontsize: 130%
    page-layout: full
    toc: true
    
execute:
  freeze: auto
