project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  favicon: static/bsa-favicon.png
  title: "Analytical Code Assurance" 
  navbar:
    title: false
    logo: "static/logo-nhs.svg"
    logo-alt: "NHS logo"
    pinned: true
    background: "#005EB8"
    left:
      - href: index.qmd
        text: Home
      - text: "Guidance"
        menu:
          - href: guidance/01-principles/index.qmd
          
    right:
      - about.qmd
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - index.qmd
      - guidance/01-principles/index.qmd
      # - section: "Analytical Cycle"
      #   contents:        
      #     - guidance/02-analytical-cycle/index.qmd
      #     - guidance/02-analytical-cycle/pages/03-customer-engagement.qmd
      #     - guidance/02-analytical-cycle/pages/04-analysis-design.qmd
      #     - guidance/02-analytical-cycle/pages/05-conducting-the-analysis.qmd
      #     - guidance/02-analytical-cycle/pages/06-delivery-and-approval.qmd
      #     - guidance/02-analytical-cycle/pages/07-approval-and-distribution.qmd
      #     - guidance/02-analytical-cycle/pages/08-review.qmd        
      # - section: "Responsibilities"
      #   contents:            
      #     - guidance/03-responsibilities/pages/09-commissioner-responsibilities.qmd
      #     - guidance/03-responsibilities/pages/10-analyst-responsibilities.qmd
      #     - guidance/03-responsibilities/pages/11-critical-friend.qmd
      

format:
  html:
   grid: 
    sidebar-width: 25%
   pagetitle: "Analytical Code Assurance"
   lang: en-GB
   theme: cosmo
   css: styles.css
   mainfont: "Arial"
   fontsize: 130%
   page-layout: full
   toc: true
    
execute:
  freeze: auto
