project:
  type: website

website:
  title: "NHSBSA code assurance"
  navbar:
    title: false
    pinned: true
    background: "#005EB8"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: en-GB



