---
title: "Documented"
description: "Clear documentation is essential for any project to be **transparent**, **reproducible** and **quality assured**."
---

> ## Suggested reading
>
> * [AF Duck book: Code documentation][duck-book-code-doc]
> * [AF Duck book: Project documentation][duck-book-project-doc]
> * [NHSBSA DDaT playbook: Licensing software or code][ddat-playbook-licenses]
> * [NHSBSA DDaT playbook: Standard code repository files][ddat-playbook-dev-doc]

## What is documentation?
Documentation is written information that explains what your analytical project does, why decisions were made, and how others can use and reproduce your work.

We should document:

* a project's purpose and scope
* how to setup the project and install any dependencies
* how to configure, use and run the code, including analytical pipelines, dashboards or webapps
* outputs from running the code and how to interpret them
* assumptions and limitations, how they are implemented and how they affect results
* key decisions and changes across a project lifecycle
* quality assurance logs 


## Why should we document our code?

Good documentation:

* Helps the intended audience understand the project using suitable language
* Makes the project accessible to a wider audience and improves transparency
* Helps to ensure the project is reusable and the results are reproducible 
* Supports knowledge sharing and collaboration between team members
* Reduces the risk of knowledge loss when team members change
* Provides an audit trail and evidence that sufficient quality assurance has taken place 
* Reflects the current state of the project and evolves as the project is updated

### Alignment with analytical code key principles

* **Transparent:** Others can more easily understand what the analysis does, with important context like decisions and limitations.
* **Reproducible:** Although not making the code inherently reproducible, reproducing it is made easier and trust is built.
* **Quality assured:** It is easier for others to review both the code and project as a whole.

## How do we create and maintain quality documentation?

Documentation should cover both the overall project and the code itself.

* **In general:**
  * Make documentation part of your normal workflow from the beginning.
  * Use simple language at an appropriate level for your readers.
  * Explain the reasons behind decisions, especially when they're not obvious.
  * Put documentation where people expect to find it, using common filenames and formats.
  * Make documentation easy to find and link related documents together.
  * Make sure someone is responsible for creating and maintaining each part of the documentation.
  * Use templates to keep documentation consistent.

* **At a project-Level:**
  * Use the standard files described in the [NHSBSA DDaT playbook][ddat-playbook-dev-doc]. Similar documentation should exist even when not using version control, such as in low-code or no-code projects.
  * You may also need extra documentation depending on your project:
    * A high-level overview or design document for complex projects.
    * How users can get help, especially for apps or interactive outputs.
    * Accessibility statements are required for any webpage or app output.

* **Within the code:**
  * Use comments in code to explain why code is written how it is (i.e. the reasoning, complex logic, and trade-offs). 
  * However, we should also avoid explaining *what* code is doing: as a rule, if code can't be understood without comments, then it is better to refactor.
  * Write standard comments that describe the reusable parts of your code (e.g. functions) - what they do, what inputs they need, what they return, and how to use them.
  * Use tools that create documentation automatically from code comments.
  * Create separate documents for complex algorithms, data structures, or specific parts of the code when needed.

**Lookout for:**

* [critical friends][critical-friend] and other [peer-reviewers][peer-review] should consider and feedback on documentation, in addition to code and outputs
* creating and updating documentation is often overlooked during project planning: be sure to allocate sufficient time for documentation in your estimates
* include documentation in retrospective discussions to ensure it's improving and evolving in line with the rest of the analysis


[duck-book-code-doc]: https://best-practice-and-impact.github.io/qa-of-code-guidance/code_documentation.html
[duck-book-project-doc]: https://best-practice-and-impact.github.io/qa-of-code-guidance/project_documentation.html
[ddat-playbook-licenses]: https://nhsbsa.github.io/nhsbsa-digital-playbook/development/coding-licences/
[ddat-playbook-dev-doc]: https://nhsbsa.github.io/nhsbsa-digital-playbook/development/dev-documentation/
[accessible]: /guidance/04-readable/index.qmd
[critical-friend]: https://nhsbsa-data-analytics.github.io/nhsbsa-data-science-playbook/guidance/03-analysis/analysis-steps/04-review.html#critical-friend-review
[peer-review]: /guidance/03-peer-reviewed/index.qmd
